# Generated by Django 5.2.2 on 2025-06-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kompyuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kompyuter nomi')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('cpu', models.CharField(max_length=100, verbose_name='Protsessor (CPU)')),
                ('ram', models.IntegerField(verbose_name='RAM (GB)')),
                ('storage', models.CharField(max_length=100, verbose_name='Xotira turi va hajmi')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ekran o‘lchami (dyuym)')),
                ('color', models.CharField(max_length=50, verbose_name='Rangi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (so‘m)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chegirma narxi (so‘m)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kompyuter_App/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qo‘shilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Kompyuter',
                'ordering': ['-created_at'],
            },
        ),
    ]
